### PR TITLE
fix: changed dispose to be  parallel

### PR DESCRIPTION
**Pull request by daomry**
related to issue https://github.com/wixplosives/component-studio/issues/11447

### CODE REVIEW

**Comment by daomry** [comment]
see also https://github.com/wixplosives/core3-utils/pull/123

**Comment by daomry** [comment]
Note: this fix only gets the time down to 25 sec on my machine, the core issue is in closing  our webpack middleware. I'm still investigating that

**Comment by YardenPorat** [comment]
I'm not sure if the disposal order is not important. @thehulke  can you assist?

**Comment by thehulke** [comment]
@daomry is this behavior tested against WCS?

IMO order here is important, since you cannot control the flow it can lead to all sorts of issues.

**Comment by YardenPorat** [comment]
I wonder who holds it up when it's sequential. Maybe we can console.time the dispose time on some debug logging

**Comment by daomry** [comment]
the holdup is in the shutdown of the webpack middleware of engine's devserver, specifically closing watches. see
https://github.com/wixplosives/engine/blob/4b3bee54f222129a566db7599e484a2cb22b105b/packages/engineer/src/feature/dev-server.dev-server.env.ts#L241-L246
 it's likely due to open handles within the electron up but I'm still investigating

**Pull request closed without merging**
