### PR TITLE
infra(docusaurus): migrate to Docusaurus 3 and include it to `package.json`

### PR DESCRIPTION
**Pull request by plisovyi**

### CODE REVIEW

**Review by Ari-Kishon — APPROVED** [review]

**Comment by AviVahl** [comment]
Are you both aware of the reasons it was not included in the repository in the first place?

**Comment by AviVahl** [comment]
Ah, it was you back then: https://github.com/wixplosives/engine/pull/2012
What changed? Is it 0 vulnerabilities now?

**Comment by plisovyi** [comment]
> Are you both aware of the reasons it was not included in the repository in the first place?

It was concerns about Docusaurus2 dependencies, right? And in Docusaurus3 they migrated to all new dependencies and there are no security audit issues anymore.

**Comment by plisovyi** [comment]
> Is it 0 vulnerabilities now?

Exactly 🤓 

>npm init docusaurus@latest my-website classic

...

> added 1242 packages, and audited 1243 packages in 55s
> 
> 294 packages are looking for funding
>  run `npm fund` for details
> 
> found 0 vulnerabilities

**Comment by AviVahl** [comment]
TBH, it wasn't just the vulnerabilities, but also what caused them. Docusaurus almost doubled the number of dependencies in this repository. We found it to be barely maintained at times, with tech debts staying around for years before getting fixed.

**Pull request merged**
