### PR TITLE
fix(deps): Reverted electron and playwright versions update

### PR DESCRIPTION
**Pull request by olehrakwix**
Revert major and minor version update for electron and playwright

### CODE REVIEW

**Review by cylon3035 — APPROVED** [review]

**Comment by AviVahl** [comment]
Why are these two being reverted?

**Comment by olehrakwix** [comment]
@AviVahl , because with new versions there are issues in WCS... electron tests are failing for unknown reasons, and there is no playwright installed on CI agent:
https://github.com/wixplosives/component-studio/actions/runs/3152189057/jobs/5127085763

**Comment by AviVahl** [comment]
Electron version here is a devDep, and shouldn't affect which version is used by consumers. Missing playwright binary happens when the installed version of playwright-chromium does not match playwright-core. Mixing of versions can cause this.

**Comment by AviVahl** [comment]
Also this repo is public. Avoid referring to private projects.

**Pull request merged**
